create table play_actions
(
    season                     integer,
    game_id                    text,
    week                       integer,
    drive                      double precision,
    down                       double precision,
    drive_id                   text,
    yrdln                      text,
    ydstogo                    double precision,
    yards_to_goal              bigint,
    ydsnet                     double precision,
    yards_gained               double precision,
    play_counter               double precision,
    play_id                    text,
    play_type                  text,
    action                     text,
    game_seconds_remaining     double precision,
    goal_to_go                 double precision,
    side_of_field              text,
    home_team                  text,
    away_team                  text,
    posteam                    text,
    posteam_score              double precision,
    posteam_score_post         double precision,
    posteam_timeouts_remaining double precision,
    defteam                    text,
    defteam_score              double precision,
    defteam_score_post         double precision,
    home_score                 integer,
    away_score                 integer,
    score_differential         double precision,
    score_differential_post    double precision,
    total_away_score           double precision,
    total_home_score           double precision,
    offense_yards_gained       double precision,
    defense_yards_gained       double precision,
    old_game_id                text,
    pass_attempt               double precision,
    rush_attempt               double precision,
    kickoff_attempt            double precision,
    punt_attempt               double precision,
    field_goal_attempt         double precision,
    two_point_attempt          double precision,
    extra_point_attempt        double precision,
    timeout                    double precision,
    penalty                    double precision,
    qb_spike                   double precision,
    "desc"                     text,
    ops_load_timestamp         timestamp
);

create table game_drive
(
    drive_id                 text,
    game_id                  text,
    play_id                  text,
    play_counter             double precision,
    drive_end_yard_line      text,
    drive_end_transition     text,
    drive_quarter_end        double precision,
    drive_ended_with_score   double precision,
    drive_start_yard_line    text,
    drive_play_id_started    double precision,
    drive_quarter_start      double precision,
    drive_start_transition   text,
    drive_inside20           double precision,
    drive_yards_penalized    double precision,
    series                   double precision,
    series_result            text,
    series_success           double precision,
    drive_game_clock_end     text,
    drive_time_of_possession text,
    drive_first_downs        double precision,
    drive_game_clock_start   text,
    drive_play_id_ended      double precision,
    drive_play_count         double precision,
    ops_load_timestamp       timestamp
);

create table play_analytics
(
    season                    integer,
    week                      integer,
    game_id                   text,
    home_team                 text,
    away_team                 text,
    posteam                   text,
    defteam                   text,
    play_id                   text,
    play_counter              double precision,
    no_score_prob             double precision,
    opp_fg_prob               double precision,
    opp_safety_prob           double precision,
    opp_td_prob               double precision,
    fg_prob                   double precision,
    safety_prob               double precision,
    td_prob                   double precision,
    extra_point_prob          double precision,
    two_point_conversion_prob double precision,
    ep                        double precision,
    epa                       double precision,
    total_home_epa            double precision,
    total_away_epa            double precision,
    total_home_rush_epa       double precision,
    total_away_rush_epa       double precision,
    total_home_pass_epa       double precision,
    total_away_pass_epa       double precision,
    air_epa                   double precision,
    yac_epa                   double precision,
    comp_air_epa              double precision,
    comp_yac_epa              double precision,
    total_home_comp_air_epa   double precision,
    total_away_comp_air_epa   double precision,
    total_home_comp_yac_epa   double precision,
    total_away_comp_yac_epa   double precision,
    total_home_raw_air_epa    double precision,
    total_away_raw_air_epa    double precision,
    total_home_raw_yac_epa    double precision,
    total_away_raw_yac_epa    double precision,
    wp                        double precision,
    def_wp                    double precision,
    home_wp                   double precision,
    away_wp                   double precision,
    wpa                       double precision,
    vegas_wpa                 double precision,
    vegas_home_wpa            double precision,
    home_wp_post              double precision,
    away_wp_post              double precision,
    vegas_wp                  double precision,
    vegas_home_wp             double precision,
    total_home_rush_wpa       double precision,
    total_away_rush_wpa       double precision,
    total_home_pass_wpa       double precision,
    total_away_pass_wpa       double precision,
    air_wpa                   double precision,
    yac_wpa                   double precision,
    comp_air_wpa              double precision,
    comp_yac_wpa              double precision,
    total_home_comp_air_wpa   double precision,
    total_away_comp_air_wpa   double precision,
    total_home_comp_yac_wpa   double precision,
    total_away_comp_yac_wpa   double precision,
    total_home_raw_air_wpa    double precision,
    total_away_raw_air_wpa    double precision,
    total_home_raw_yac_wpa    double precision,
    total_away_raw_yac_wpa    double precision,
    qb_epa                    double precision,
    xyac_epa                  double precision,
    xyac_mean_yardage         double precision,
    xyac_median_yardage       double precision,
    xyac_success              double precision,
    xyac_fd                   double precision,
    xpass                     double precision,
    pass_oe                   double precision,
    ops_load_timestamp        timestamp
);

create table play_situations
(
    drive_id                   text,
    game_id                    text,
    play_id                    text,
    play_counter               double precision,
    away_score                 integer,
    defteam_score              double precision,
    defteam_score_post         double precision,
    posteam_score              double precision,
    posteam_score_post         double precision,
    score_differential         double precision,
    score_differential_post    double precision,
    total_away_score           double precision,
    total_home_score           double precision,
    time                       text,
    time_of_day                text,
    defteam_timeouts_remaining double precision,
    away_timeouts_remaining    double precision,
    play_clock                 text,
    home_timeouts_remaining    double precision,
    posteam_timeouts_remaining double precision,
    qtr                        double precision,
    game_half                  text,
    yrdln                      text,
    down                       double precision,
    half_seconds_remaining     double precision,
    goal_to_go                 double precision,
    quarter_end                double precision,
    game_seconds_remaining     double precision,
    drive                      double precision,
    ydstogo                    double precision,
    quarter_seconds_remaining  double precision,
    side_of_field              text,
    timeout_team               text,
    ops_load_timestamp         timestamp
);

create table play_metrics
(
    season                integer,
    week                  integer,
    drive_id              text,
    game_id               text,
    play_id               text,
    play_counter          double precision,
    pass_attempt          double precision,
    rush_attempt          double precision,
    kickoff_attempt       double precision,
    punt_attempt          double precision,
    field_goal_attempt    double precision,
    extra_point_attempt   double precision,
    touchdown             double precision,
    touchback             double precision,
    safety                double precision,
    fumble                double precision,
    complete_pass         double precision,
    incomplete_pass       double precision,
    interception          double precision,
    sack                  double precision,
    penalty               double precision,
    two_point_conv_result text,
    two_point_attempt     double precision,
    qb_spike              double precision,
    qb_kneel              double precision,
    penalty_yards         double precision,
    ops_load_timestamp    timestamp
);

create table player_events
(
    season             bigint,
    week               bigint,
    game_id            text,
    posteam            text,
    defteam            text,
    play_counter       text,
    player_id          text,
    event              text,
    play_id            text,
    lineup             text,
    game_order         text,
    team               text,
    ops_load_timestamp timestamp
);

create table game_info
(
    season               integer,
    game_id              text,
    stadium              text,
    div_game             integer,
    home_opening_kickoff double precision,
    stadium_id           text,
    season_type          text,
    week                 integer,
    roof                 text,
    weather              text,
    home_team            text,
    old_game_id          text,
    wind                 double precision,
    location             text,
    game_stadium         text,
    temp                 double precision,
    surface              text,
    away_team            text,
    total_line           double precision,
    game_date            text,
    start_time           text,
    home_score           integer,
    away_score           integer,
    away_coach           text,
    home_coach           text,
    ops_load_timestamp   timestamp
);

create table player_participation
(
    season             bigint,
    game_id            text,
    game_order         text,
    play_id            text,
    team               text,
    player_id          text,
    lineup             text,
    ops_load_timestamp timestamp
);

create table injuries
(
    season                    double precision,
    game_type                 text,
    team                      text,
    week                      double precision,
    player_id                 text,
    position                  text,
    full_name                 text,
    first_name                text,
    last_name                 text,
    report_primary_injury     text,
    report_secondary_injury   text,
    report_status             text,
    practice_primary_injury   text,
    practice_secondary_injury text,
    practice_status           text,
    date_modified             timestamp with time zone,
    op_source                 text,
    primary_injury            text,
    ops_load_timestamp        timestamp
);

create table players
(
    status                   text,
    display_name             text,
    first_name               text,
    last_name                text,
    esb_id                   text,
    player_id                text,
    suffix                   text,
    birth_date               text,
    college_name             text,
    position_group           text,
    position                 text,
    jersey_number            double precision,
    height                   text,
    weight                   text,
    team_abbr                text,
    team_seq                 double precision,
    current_team_id          text,
    football_name            text,
    entry_year               double precision,
    rookie_year              double precision,
    draft_club               text,
    college_conference       text,
    status_description_abbr  text,
    status_short_description text,
    gsis_it_id               double precision,
    short_name               text,
    smart_id                 text,
    headshot                 text,
    draft_number             double precision,
    uniform_number           text,
    draft_round              text,
    season                   double precision,
    op_source                text,
    ops_load_timestamp       timestamp
);

create table player_stats
(
    player_id                   text,
    player_name                 text,
    player_display_name         text,
    position                    text,
    position_group              text,
    headshot_url                text,
    team                        text,
    season                      integer,
    week                        integer,
    season_type                 text,
    completions                 integer,
    attempts                    integer,
    passing_yards               double precision,
    passing_tds                 integer,
    interceptions               double precision,
    sacks                       double precision,
    sack_yards                  double precision,
    sack_fumbles                integer,
    sack_fumbles_lost           integer,
    passing_air_yards           double precision,
    passing_yards_after_catch   double precision,
    passing_first_downs         double precision,
    passing_epa                 double precision,
    passing_2pt_conversions     integer,
    pacr                        double precision,
    dakota                      double precision,
    carries                     integer,
    rushing_yards               double precision,
    rushing_tds                 integer,
    rushing_fumbles             double precision,
    rushing_fumbles_lost        double precision,
    rushing_first_downs         double precision,
    rushing_epa                 double precision,
    rushing_2pt_conversions     integer,
    receptions                  integer,
    targets                     integer,
    receiving_yards             double precision,
    receiving_tds               integer,
    receiving_fumbles           double precision,
    receiving_fumbles_lost      double precision,
    receiving_air_yards         double precision,
    receiving_yards_after_catch double precision,
    receiving_first_downs       double precision,
    receiving_epa               double precision,
    receiving_2pt_conversions   integer,
    racr                        double precision,
    target_share                double precision,
    air_yards_share             double precision,
    wopr                        double precision,
    special_teams_tds           double precision,
    fantasy_points              double precision,
    fantasy_points_ppr          double precision,
    op_source                   text,
    primary_injury              text,
    report_status               text,
    practice_status             text,
    ops_load_timestamp          timestamp
);

create table adv_stats_def
(
    season             integer,
    player             text,
    pfr_id             text,
    tm                 text,
    age                double precision,
    pos                text,
    g                  double precision,
    gs                 double precision,
    int                double precision,
    tgt                double precision,
    cmp                double precision,
    cmp_percent        double precision,
    yds                double precision,
    yds_cmp            double precision,
    yds_tgt            double precision,
    td                 double precision,
    rat                double precision,
    dadot              double precision,
    air                double precision,
    yac                double precision,
    bltz               double precision,
    hrry               double precision,
    qbkd               double precision,
    sk                 double precision,
    prss               double precision,
    comb               double precision,
    m_tkl              double precision,
    m_tkl_percent      double precision,
    loaded             date,
    op_source          text,
    ops_load_timestamp timestamp
);

create table adv_stats_pass
(
    player             text,
    team               text,
    pass_attempts      double precision,
    throwaways         double precision,
    spikes             double precision,
    drops              double precision,
    drop_pct           double precision,
    bad_throws         double precision,
    bad_throw_pct      double precision,
    season             integer,
    pfr_id             text,
    pocket_time        double precision,
    times_blitzed      double precision,
    times_hurried      double precision,
    times_hit          double precision,
    times_pressured    double precision,
    pressure_pct       double precision,
    batted_balls       double precision,
    on_tgt_throws      double precision,
    on_tgt_pct         double precision,
    rpo_plays          double precision,
    rpo_yards          double precision,
    rpo_pass_att       double precision,
    rpo_pass_yards     double precision,
    rpo_rush_att       double precision,
    rpo_rush_yards     double precision,
    pa_pass_att        double precision,
    pa_pass_yards      double precision,
    op_source          text,
    ops_load_timestamp timestamp
);

create table adv_stats_rec
(
    season             integer,
    player             text,
    pfr_id             text,
    tm                 text,
    age                double precision,
    pos                text,
    g                  double precision,
    gs                 double precision,
    tgt                double precision,
    rec                double precision,
    yds                double precision,
    td                 double precision,
    x1d                double precision,
    ybc                double precision,
    ybc_r              double precision,
    yac                double precision,
    yac_r              double precision,
    adot               double precision,
    brk_tkl            double precision,
    rec_br             double precision,
    drop               double precision,
    drop_percent       double precision,
    int                double precision,
    rat                double precision,
    loaded             date,
    op_source          text,
    ops_load_timestamp timestamp
);

create table adv_stats_rush
(
    season             integer,
    player             text,
    pfr_id             text,
    tm                 text,
    age                double precision,
    pos                text,
    g                  double precision,
    gs                 double precision,
    att                double precision,
    yds                double precision,
    td                 double precision,
    x1d                double precision,
    ybc                double precision,
    ybc_att            double precision,
    yac                double precision,
    yac_att            double precision,
    brk_tkl            double precision,
    att_br             double precision,
    loaded             date,
    op_source          text,
    ops_load_timestamp timestamp
);

create table nextgen_pass
(
    season                                  bigint,
    season_type                             text,
    week                                    bigint,
    player_display_name                     text,
    player_position                         text,
    team_abbr                               text,
    avg_time_to_throw                       double precision,
    avg_completed_air_yards                 double precision,
    avg_intended_air_yards                  double precision,
    avg_air_yards_differential              double precision,
    aggressiveness                          double precision,
    max_completed_air_distance              double precision,
    avg_air_yards_to_sticks                 double precision,
    attempts                                bigint,
    pass_yards                              bigint,
    pass_touchdowns                         bigint,
    interceptions                           bigint,
    passer_rating                           double precision,
    completions                             bigint,
    completion_percentage                   double precision,
    expected_completion_percentage          double precision,
    completion_percentage_above_expectation double precision,
    avg_air_distance                        double precision,
    max_air_distance                        double precision,
    player_gsis_id                          text,
    player_first_name                       text,
    player_last_name                        text,
    player_jersey_number                    bigint,
    player_short_name                       text,
    op_source                               text,
    ops_load_timestamp                      timestamp
);

create table nextgen_rec
(
    season                              bigint,
    season_type                         text,
    week                                bigint,
    player_display_name                 text,
    player_position                     text,
    team_abbr                           text,
    avg_cushion                         double precision,
    avg_separation                      double precision,
    avg_intended_air_yards              double precision,
    percent_share_of_intended_air_yards double precision,
    receptions                          bigint,
    targets                             bigint,
    catch_percentage                    double precision,
    yards                               double precision,
    rec_touchdowns                      bigint,
    avg_yac                             double precision,
    avg_expected_yac                    double precision,
    avg_yac_above_expectation           double precision,
    player_gsis_id                      text,
    player_first_name                   text,
    player_last_name                    text,
    player_jersey_number                bigint,
    player_short_name                   text,
    op_source                           text,
    ops_load_timestamp                  timestamp
);

create table nextgen_rush
(
    season                               bigint,
    season_type                          text,
    week                                 bigint,
    player_display_name                  text,
    player_position                      text,
    team_abbr                            text,
    efficiency                           double precision,
    percent_attempts_gte_eight_defenders double precision,
    avg_time_to_los                      double precision,
    rush_attempts                        bigint,
    rush_yards                           bigint,
    expected_rush_yards                  double precision,
    rush_yards_over_expected             double precision,
    avg_rush_yards                       double precision,
    rush_yards_over_expected_per_att     double precision,
    rush_pct_over_expected               double precision,
    rush_touchdowns                      bigint,
    player_gsis_id                       text,
    player_first_name                    text,
    player_last_name                     text,
    player_jersey_number                 bigint,
    player_short_name                    text,
    op_source                            text,
    ops_load_timestamp                   timestamp
);


